import type { ReactNode } from "react";
import { cn } from "@/lib/cn";
import type { Provenance } from "@/lib/ai/types";

/**
 * Provenance label for anything the AI layer produced.
 *
 * This component is the enforcement point for a product rule: no generated
 * content is displayed without saying who produced it, whether a model was
 * actually involved, and what it was derived from.
 */
export function AIProvenance({
  provenance,
  className,
}: {
  provenance: Provenance;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "rounded-md border border-accent-200 bg-accent-50 px-3 py-2 text-[0.82rem] text-accent-700",
        className,
      )}
    >
      <p className="font-semibold">
        <span aria-hidden="true">◆</span>{" "}
        {provenance.isSimulated
          ? "Sample output — no AI provider is configured"
          : `Generated by ${provenance.providerLabel}${
              provenance.model ? ` (${provenance.model})` : ""
            }`}
      </p>
      <p className="mt-1">{provenance.sourceNote}</p>
      {provenance.isSimulated ? (
        <p className="mt-1">
          This text was assembled by deterministic prototype logic from content
          already in the course. It is shown to demonstrate the workflow, not to
          suggest a model is running.
        </p>
      ) : null}
    </div>
  );
}

/** Compact inline marker for a single generated field or list item. */
export function AIGeneratedTag({
  simulated = true,
  className,
}: {
  simulated?: boolean;
  className?: string;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded border border-accent-200 bg-accent-50 px-1.5 py-0.5 text-[0.68rem] font-medium uppercase tracking-wide text-accent-700",
        className,
      )}
    >
      <span aria-hidden="true">◆</span>
      {simulated ? "Sample AI draft" : "AI draft"}
    </span>
  );
}

/**
 * Wrapper for course-wide generated material awaiting professor approval.
 * Makes the review requirement visible rather than assumed.
 */
export function NeedsReviewFrame({
  approved,
  children,
  className,
}: {
  approved: boolean;
  children: ReactNode;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "rounded-lg border-2 border-dashed p-4",
        approved ? "border-track-200 bg-track-50" : "border-accent-200 bg-accent-50/40",
        className,
      )}
    >
      <p
        className={cn(
          "mb-3 text-[0.78rem] font-semibold uppercase tracking-wide",
          approved ? "text-track-600" : "text-accent-700",
        )}
      >
        {approved
          ? "Reviewed and approved by the professor"
          : "Draft — not visible to students until a professor approves it"}
      </p>
      {children}
    </div>
  );
}
